require('impatient')
require('caligula.set')
require('caligula.plugins')
require('caligula.lsp')
require('caligula.lsp.cmp')
require('caligula.plugins.lualine')
require('caligula.plugins.gitsigns')
require('caligula.plugins.autopairs')
