#!/bin/zsh
brew install --cask alfred
brew install --cask visual-studio-code
brew install --cask calibre
brew install --cask iterm2
brew install --cask insomnia
brew install --cask musicbrainz-picard
brew install --cask via
brew install --cask radio-silence
brew install --cask tableplus
brew install --cask onyx
brew install --cask malwarebytes
brew install --cask figma
brew install --cask 1password
brew install --cask google-chrome
brew install --cask spotify
brew install --cask discord
brew install --cask signal
brew install --cask grandperspective
brew install --cask stats
brew install --cask hiddenbar
brew install --cask slack
brew install --cask balenaetcher
brew install --cask cloudflare-warp
brew install --cask iina
brew install --cask imageoptim
brew install --cask keka
brew install --cask little-snitch
brew install --cask mullvadvpn
brew install nicotine-plus
brew install --cask notion
brew install --cask obs
brew install --cask parallels
brew install --cask playcover
brew install --cask minecraft
brew install --cask plex
brew install --cask plexamp
brew install --cask raspberry-pi-imager
brew install --cask responsively
brew install --cask steam
brew install --cask transmission
brew install --cask ubar
brew install --cask utm
brew install --cask warp
brew install --cask ferdi
brew install --cask github

